### ISSUE TITLE
我设置了用户名和密码，但是连上不服务器，返回407

### ISSUE THREAD

**Issue by liaogang** [mikaelbo/ProxySwitcher#1]

**Comment by mikaelbo** [comment]
由于还没找到在Apple Keychain哪里保存用户和密码，你需要先开Safari。它让你输入用户和密码的时候，这些信息已经填好了。你按OK就可以开始用了。

**Comment by liaogang** [comment]
这样啊，我这边的情况是每次打开一个新标签的时候都要输用户和密码

**Comment by 5t4r** [comment]
先在WiFi里设置好代理账号密码什么的，再用KeychainDumper把keychain dump all出来就能看到代理的账号密码在那个group下了。然后通过设置keychain就可以做到设置账号密码了。

**Comment by mikaelbo** [comment]
你做过了吗？这我早就试了。用KeychainDumper，看看是哪个Group。可在Keychain保存之后，iOS还是不会用的。有可能是我做错了。你能做到的话，请做个pr！～

**Comment by liaogang** [comment]
@5t4r iOS现在在连接代理时不支持用户名和密码的认证。　无论是http代理还是socks代理。　我自己测试过，你们可以在wifi设置填一个要认证的代理测试一下。
